### ISSUE TITLE
Submit from Remote Machine

### ISSUE THREAD

**Issue by zanussbaum** [AIR-Bench/AIR-Bench#31]
Is there a way to add functionality to submit results from a remote machine? Right now it takes a little bit of time to run the results on the remote, download the zip, then upload to the leaderboard. Most of the time is spent `scp`'ing from machines and would be great if we could send the results directly from the machine!

**Comment by hanhainebula** [comment]
Hi, @zanussbaum! I'm sorry we didn't consider this in our design. We will consider implementing this in the future. But currently, a possible solution is to use [HF's API](https://huggingface.co/docs/hub/en/models-adding-libraries#uploadfile) on the remote machine to upload .zip files to your HF dataset. Then download and submit it on your local computer. I hope this can temporarily alleviate this problem.

**Comment by zanussbaum** [comment]
no worries! happy to contribute a solution if there is a simple one to submit directly to the benchmark!
